
modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="deepblue"
version="${1.0}"
displayName="DragN's Aquatics: Deep Blue Addon"
logoFile="deepblue.png"
authors="DragN0007"
description='''
An addon for DragN's Bettas & Aquatics. Adds large marine animals and commercial aquarium decor!
'''

[[dependencies.deepblue]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.deepblue]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"

[[dependencies.deepblue]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.0.57,)"
ordering="NONE"
side="BOTH"

[[dependencies.deepblue]]
modId = "bettas"
mandatory = true
versionRange = "[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.deepblue]]
modId = "terrablender"
mandatory = true
versionRange = "[1.2.0.126,)"
ordering="NONE"
side="BOTH"

